sonar.organization=mickeymeowmeow
sonar.projectKey=mickeymeowmeow_generals-plus
sonar.projectName=Generals Plus

sonar.sources=apps,packages
sonar.tests=apps,packages

sonar.test.inclusions=**/*.test.ts,**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.d.ts

sonar.typescript.node=node
