import type { ISeatReservation } from "@colyseus/sdk/Client";
import type { ICoordinate, IGameResult } from "@generals-plus/engine";
import { ActionType, GameStatus, PlayerStatus } from "@generals-plus/engine";
import type {
  ActionData,
  MatchClientMessagePayload,
  MatchServerMessagePayload,
  MatchState,
  Player,
} from "@generals-plus/shared-types";
import {
  MatchClientMessage,
  MatchServerMessage,
} from "@generals-plus/shared-types";
import { useCallback, useEffect, useRef, useState } from "react";

import type { RenderGrid } from "#/features/game/renderer/render-grid";
import type { RenderScoreboardData } from "#/features/game/renderer/scoreboard-types";
import { createRenderGrid } from "#/features/game/utils/grid-adapter";
import type { MoveIntent } from "#/features/game/utils/move";
import { MoveDirection } from "#/features/game/utils/move";
import { scoreboardAdapter } from "#/features/game/utils/scoreboard-adapter";
import { networkProvider } from "#/infra/network/provider";
import type { RoomClient } from "#/infra/network/room";

type GameRoomClient = RoomClient<
  MatchState,
  MatchClientMessagePayload,
  MatchServerMessagePayload
>;

function getDirection(from: ICoordinate, to: ICoordinate): MoveDirection {
  if (to.y < from.y) return MoveDirection.UP;
  if (to.y > from.y) return MoveDirection.DOWN;
  if (to.x < from.x) return MoveDirection.LEFT;
  return MoveDirection.RIGHT;
}

export function useGameRoom(
  reservation: ISeatReservation,
  currentUserId: string | null,
) {
  const [room, setRoom] = useState<GameRoomClient | null>(null);
  const [renderGrid, setRenderGrid] = useState<RenderGrid | null>(null);
  const [moveQueue, setMoveQueue] = useState<MoveIntent[]>([]);
  const [gameState, setGameState] = useState<MatchState | null>(null);
  const [scoreboard, setScoreboard] = useState<RenderScoreboardData | null>(
    null,
  );
  const [localPlayer, setLocalPlayer] = useState<Player | null>(null);
  const [gameResult, setGameResult] = useState<IGameResult | null>(null);
  const [playerColors, setPlayerColors] = useState<Map<string, number>>(
    new Map(),
  );
  // Explicit exit and effect cleanup both call `leave()`, so gate the second
  // path to avoid duplicate disconnect requests during settlement navigation.
  const didLeaveRoomRef = useRef(false);

  const isEliminated = localPlayer?.status === PlayerStatus.ELIMINATED;
  const isFinished =
    gameState?.status === GameStatus.FINISHED || gameResult !== null;

  useEffect(() => {
    if (!reservation) return;
    didLeaveRoomRef.current = false;
    setGameResult(null);
    console.log(
      "Received seat reservation, connecting to game room...",
      reservation,
    );
    let currentRoom: GameRoomClient;

    const connect = async () => {
      try {
        // Use the reservation generated by the SetupRoom to enter the MatchRoom
        currentRoom = await networkProvider.consumeSeatReservation(reservation);
        setRoom(currentRoom);
        // The server broadcasts the final result before disconnecting everyone,
        // which lets the client keep a winner banner even after room state stops
        // advancing.
        currentRoom.onMessage(MatchServerMessage.GAME_END, (result) => {
          setGameResult(result);
        });

        currentRoom.onStateChange((state) => {
          setGameState(state);

          const colorMap = new Map<string, number>();
          // The renderer only needs public identity/color metadata here; the
          // private `players` view is not available to other clients.
          state.publicPlayers.forEach((player, playerId) => {
            colorMap.set(playerId, player.color);
          });
          setPlayerColors(colorMap);
          // Scoreboard rows are derived client-side so we can highlight the
          // local user without changing the shared room schema.
          setScoreboard(scoreboardAdapter.fromMatchState(state, currentUserId));
          setLocalPlayer(
            currentUserId ? (state.players.get(currentUserId) ?? null) : null,
          );

          const myId = currentRoom.sessionId;

          const myVision = state.clientVisions.get(myId);
          if (myVision && state.width > 0) {
            const newGrid = createRenderGrid(
              myVision,
              state.width,
              state.height,
            );
            setRenderGrid(newGrid);
          }

          const myQueue = state.clientActionQueues.get(myId);
          if (myQueue) {
            const newQueue = myQueue.queue.map((action: ActionData) => ({
              from: { x: action.fromX, y: action.fromY },
              direction: getDirection(
                { x: action.fromX, y: action.fromY },
                { x: action.toX, y: action.toY },
              ),
            }));
            setMoveQueue(newQueue);
          }
        });
      } catch (error) {
        console.error("Failed to consume seat reservation", error);
      }
    };

    connect();

    return () => {
      if (currentRoom && !didLeaveRoomRef.current) currentRoom.leave();
    };
  }, [currentUserId, reservation]);

  const sendMove = useCallback(
    (from: ICoordinate, to: ICoordinate) => {
      if (!room || !localPlayer || isEliminated || isFinished) return;
      room.send(MatchClientMessage.ACTION, {
        playerId: room.sessionId,
        type: ActionType.MOVE,
        from,
        to,
      });
    },
    [isEliminated, isFinished, localPlayer, room],
  );

  const leaveRoom = useCallback(async () => {
    if (!room || didLeaveRoomRef.current) return;
    didLeaveRoomRef.current = true;
    await room.leave(true);
  }, [room]);

  return {
    room,
    renderGrid,
    moveQueue,
    gameState,
    scoreboard,
    gameResult,
    localPlayer,
    isEliminated,
    isFinished,
    leaveRoom,
    sendMove,
    playerColors,
  };
}
