import type { ISeatReservation } from "@colyseus/sdk/Client";
import type { ICoordinate } from "@generals-plus/engine";
import { ActionType } from "@generals-plus/engine";
import type {
  ActionData,
  MatchClientMessagePayload,
  MatchServerMessagePayload,
  MatchState,
} from "@generals-plus/shared-types";
import { useEffect, useState } from "react";

import type { RenderGrid } from "#/features/game/renderer/render-grid";
import { createRenderGrid } from "#/features/game/utils/grid-adapter";
import type { MoveIntent } from "#/features/game/utils/move";
import { MoveDirection } from "#/features/game/utils/move";
import { networkProvider } from "#/infra/network/provider";
import type { RoomClient } from "#/infra/network/room";

type GameRoomClient = RoomClient<
  MatchState,
  MatchClientMessagePayload,
  MatchServerMessagePayload
>;

function getDirection(from: ICoordinate, to: ICoordinate): MoveDirection {
  if (to.y < from.y) return MoveDirection.UP;
  if (to.y > from.y) return MoveDirection.DOWN;
  if (to.x < from.x) return MoveDirection.LEFT;
  return MoveDirection.RIGHT;
}

export function useGameRoom(reservation: ISeatReservation) {
  const [room, setRoom] = useState<GameRoomClient | null>(null);
  const [renderGrid, setRenderGrid] = useState<RenderGrid | null>(null);
  const [moveQueue, setMoveQueue] = useState<MoveIntent[]>([]);
  const [gameState, setGameState] = useState<MatchState | null>(null);
  const [playerColors, setPlayerColors] = useState<Map<string, number>>(
    new Map(),
  );

  useEffect(() => {
    if (!reservation) return;
    console.log(
      "Received seat reservation, connecting to game room...",
      reservation,
    );
    let currentRoom: GameRoomClient;

    const connect = async () => {
      try {
        // Use the reservation generated by the SetupRoom to enter the MatchRoom
        currentRoom = await networkProvider.consumeSeatReservation(reservation);
        setRoom(currentRoom);

        currentRoom.onStateChange((state) => {
          setGameState(state);

          const colorMap = new Map<string, number>();
          state.playerColors.forEach((color, playerId) => {
            colorMap.set(playerId, color);
          });
          setPlayerColors(colorMap);

          const myId = currentRoom.sessionId;

          const myVision = state.clientVisions.get(myId);
          if (myVision && state.width > 0) {
            const newGrid = createRenderGrid(
              myVision,
              state.width,
              state.height,
            );
            setRenderGrid(newGrid);
          }

          const myQueue = state.clientActionQueues.get(myId);
          if (myQueue) {
            const newQueue = myQueue.queue.map((action: ActionData) => ({
              from: { x: action.fromX, y: action.fromY },
              direction: getDirection(
                { x: action.fromX, y: action.fromY },
                { x: action.toX, y: action.toY },
              ),
            }));
            setMoveQueue(newQueue);
          }
        });
      } catch (error) {
        console.error("Failed to consume seat reservation", error);
      }
    };

    connect();

    return () => {
      if (currentRoom) currentRoom.leave();
    };
  }, [reservation]);

  const sendMove = (from: ICoordinate, to: ICoordinate) => {
    if (!room) return;
    room.send("action", {
      playerId: room.sessionId,
      type: ActionType.MOVE,
      from,
      to,
    });
  };

  return { room, renderGrid, moveQueue, gameState, sendMove, playerColors };
}
