name: CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: alpine/git
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git push --force --no-verify https://oauth2:${{ secrets.GITLAB_TOKEN }}@${{ secrets.GITLAB_URL }} main:main
